### ISSUE TITLE
New messages counter 

### ISSUE THREAD

**Issue by myhubacct** [ShihabM/Mast#12]
Sometimes I get an new message counter at the top right side. This indicator disappears as soon as I read a thread from the new messages or start scrolling to the newer messages. This happens in timeline, mentions and likes view. 

iPhone 6
iOS 12.1
Mast 1.2.4

**Comment by ShihabM** [comment]
I believe this should now be resolved with the scroll retention fixes introduced recently.

**Comment by mcg** [comment]
This is still happening. The counter disappears if you do most anything that leaves the timeline with the counter.
