### ISSUE TITLE
not all URLs are converted to links

### ISSUE THREAD

**Issue by symbolisch1234** [ShihabM/Mast#47]
see for example https://mastodon.ar.al/@aral/101422830409329826 where the URL is a link in my web-client, but on Mast it is just text :(

**Comment by symbolisch1234** [comment]
still present in 1.4.9

**Comment by ShihabM** [comment]
Hoping to get this fixed in a future update.

**Comment by mediaformat** [comment]
Still seeing this with longer TLDs
https://pleroma.fr/objects/76fbf0cb-4cb9-4165-ab98-440276f125cf
